name: Get Previous Job Status

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: echo "Hello from the first job"
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Check previous job status
        run: echo "First job status:${{ needs.first_job.result }}"
        env:
          JOB_STATUS: ${{ needs.first_job.result }}
