name: Passing outputs of job

on:
  workflow_dispatch:
       inputs:
         Branch:
           description: 'Enter Sprint branch'
           type: string
           required: true
  workflow_call:

jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       ref: ${{ inputs.Branch }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -X package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       ref: ${{ inputs.Branch }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -X package --file pom.xml
