name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      branch:
        required: true
        type: string
      repo:
        required: true
        type: string
    secrets:
      token:
        required: true

  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        default: Soorya8docker
      branch:
        required: true
        type: string
        default: master
      repo:
        required: true
        type: string
        default: simple-java-maven-app
jobs:
  DEV:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.set_status.outputs.status }}
    steps:
    - name: Inputs branch (workflow call)
      if: ${{ inputs.branch }} != ''
      run: echo ${{ inputs.username }} ${{ inputs.branch }} ${{ inputs.repo }}
    - name: Checkout process
      uses: actions/checkout@v3 # Necessary to access local action
      with:
        repository: Soorya8docker/${{ inputs.repo }}
        path: ${{ inputs.repo }}
        ref: ${{ inputs.branch }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -X package --file ${{ inputs.repo }}/pom.xml
    - name: Move JAR files
      run: |
        mkdir -p staging
        cp ${{ inputs.repo }}/target/*.jar staging
    - name: Upload JAR files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.repo }}-jar-files
        path: staging/
    - name: Run a command
      run: echo "Hello from the first job"
    - name: Set job status as output
      id: set_status
      run: echo "::set-output name=status::${{ job.status }}"
  second_job:
    needs: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get output from first job
        run: echo "First job status is ${{ needs.DEV.outputs.job_status }}"
